import type { PromptGalleryItem } from "./types";

export const PROMPT_GALLERY_ITEMS: PromptGalleryItem[] = [
  {
    id: "keel",
    title: "Keel",
    category: "creative",
    categoryLabel: "Creative",
    image: "https://picsum.photos/seed/keel/600/780",
    width: 600,
    height: 780,
    href: "/prompts/keel",
    isPremium: true,
  },
  {
    id: "cordex",
    title: "Cordex",
    category: "technology",
    categoryLabel: "Technology",
    image: "https://picsum.photos/seed/cordex/600/520",
    width: 600,
    height: 520,
    href: "/prompts/cordex",
    hasVariations: true,
  },
  {
    id: "design-rocket",
    title: "Design Rocket",
    category: "ai",
    categoryLabel: "Ai",
    image: "https://picsum.photos/seed/design-rocket/600/680",
    width: 600,
    height: 680,
    href: "/prompts/design-rocket",
  },
  {
    id: "monolithic",
    title: "Monolithic",
    category: "saas",
    categoryLabel: "Saas",
    image: "https://picsum.photos/seed/monolithic/600/440",
    width: 600,
    height: 440,
    href: "/prompts/monolithic",
  },
  {
    id: "way-farer",
    title: "Way Farer",
    category: "travel",
    categoryLabel: "Travel",
    image: "https://picsum.photos/seed/way-farer/600/720",
    width: 600,
    height: 720,
    href: "/prompts/way-farer",
  },
  {
    id: "alethia",
    title: "Alethia",
    category: "wellness",
    categoryLabel: "Wellness",
    image: "https://picsum.photos/seed/alethia/600/560",
    width: 600,
    height: 560,
    href: "/prompts/alethia",
    isPremium: true,
  },
  {
    id: "cast-render",
    title: "Cast and Render",
    category: "3d-website",
    categoryLabel: "3D",
    image: "https://picsum.photos/seed/cast-render/600/640",
    width: 600,
    height: 640,
    href: "/prompts/cast-render",
    hasVariations: true,
  },
  {
    id: "orange-horse",
    title: "Orange Horse",
    category: "portfolio",
    categoryLabel: "Portfolio",
    image: "https://picsum.photos/seed/orange-horse/600/500",
    width: 600,
    height: 500,
    href: "/prompts/orange-horse",
    isPremium: true,
  },
  {
    id: "nova-lens",
    title: "Nova Lens",
    category: "hero",
    categoryLabel: "Hero",
    image: "https://picsum.photos/seed/nova-lens/600/760",
    width: 600,
    height: 760,
    href: "/prompts/nova-lens",
  },
  {
    id: "studio-agency",
    title: "Studio Agency",
    category: "agency",
    categoryLabel: "Agency",
    image: "https://picsum.photos/seed/studio-agency/600/480",
    width: 600,
    height: 480,
    href: "/prompts/studio-agency",
  },
  {
    id: "landing-flux",
    title: "Landing Flux",
    category: "landing-page",
    categoryLabel: "Landing Page",
    image: "https://picsum.photos/seed/landing-flux/600/600",
    width: 600,
    height: 600,
    href: "/prompts/landing-flux",
    hasVariations: true,
  },
  {
    id: "app-shell",
    title: "App Shell",
    category: "apps",
    categoryLabel: "Apps",
    image: "https://picsum.photos/seed/app-shell/600/540",
    width: 600,
    height: 540,
    href: "/prompts/app-shell",
  },
];
